version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/front
    overwrite: yes

permission:
  - object: /home/ubuntu/app/front
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root