# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      
    - name: Check Node.js Version
      run: node -v
      
    - name: Install Dependencies
      run: npm ci --frozen-lockfile
      
    - name: Build
      run: npm run build
      env:
        CI: ""

    - name: zip create
      run: zip -r -qq ./SOOMTUT_FRONT.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:
        aws s3 cp --region ap-northeast-2 ./SOOMTUT_FRONT.zip s3://soomtut-github-actions-s3-bucket/SOOMTUT_FRONT.zip
    
    - name: Deploy to EC2 from S3
      run: aws deploy create-deployment --application-name soomtut-codedeploy-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name soomtut-codedeploy-deployment-group --s3-location bucket=soomtut-github-actions-s3-bucket,key=SOOMTUT_FRONT.zip,bundleType=zip
